### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by bowerth** [elbamos/Zeppelin-With-R#2]
can anybody install this?

**Comment by rboubela** [comment]
when using scala version 2.10.5, maven 3.3.3  and :

``` bash
mvn clean package -Pspark-1.5 -DskipTests
```

the first error is:
[ERROR] /ssd/Software/incubator-zeppelin/r/src/test/scala/org/apache/zeppelin/rinterpreter/RContextSparkTest.scala:99: error: value applyDynamic is not a member of org.apache.zeppelin.rinterpreter.RContext
[ERROR] error after rewriting to RContextSparkTest.this.rcon.<applyDynamic: error>("waitOnSpark")
[INFO] possible cause: maybe a wrong Dynamic method signature?
[INFO]     rcon.waitOnSpark()
[INFO]     ^

**Comment by elbamos** [comment]
@bowerth  @rboubela  

Guys - sorry, for whatever reason I'm just seeing this now.  I'd appreciate if you can confirm that these issues are completely resolved in the current version of the code.

**Comment by elbamos** [comment]
Ok I'm gonna close this.  If you guys are still having issues, please open a new issue.
