### ISSUE TITLE
Build failed on yosemite

### ISSUE THREAD

**Issue by javadba** [elbamos/Zeppelin-With-R#4]
I ran the following command line on Yosemite:

Zeppelin-With-R $mvn package install -DskipTests -Pspark-1.5

[INFO] --- exec-maven-plugin:1.2.1:exec (default) @ zeppelin-zrinterpreter ---
ERROR: dependency ‘evaluate’ is not available for package ‘rzeppelin’
- removing ‘/shared/Zeppelin-With-R/r/lib/rzeppelin’
  [INFO] ------------------------------------------------------------------------
  [INFO] Reactor Summary:
  [INFO]
  [INFO] Zeppelin ........................................... SUCCESS [ 19.627 s]
  [INFO] Zeppelin: Interpreter .............................. SUCCESS [ 16.560 s]
  [INFO] Zeppelin: Zengine .................................. SUCCESS [  8.415 s]
  [INFO] Zeppelin: Spark dependencies ....................... SUCCESS [01:17 min]
  [INFO] Zeppelin: Spark .................................... SUCCESS [ 30.803 s]
  [INFO] Zeppelin: R Interpreter ............................ FAILURE [ 17.001 s]

**Comment by elbamos** [comment]
You need to install the R package "evaluate".  You can do that from R with install.packages("evaluate") from R.  "evaluate" is listed as a mandatory dependency in the README.  I suggest taking a look at it - there are some other things you'll want to install to get real use out of this.
