### ISSUE TITLE
error in pom.xml in r folder

### ISSUE THREAD

**Issue by smartinsightsfromdata** [elbamos/Zeppelin-With-R#9]
The current pom.xml in the folder r contains the following line at L#10:

```
0.5.5-incubating
```

This gives a mvn error.

Changing to the line below it works:

```
0.5.6-incubating-SNAPSHOT
```

**Comment by elbamos** [comment]
Thanks!  Fixed here. FYI - Since we're now (fingers-crossed!) getting closer to merge, more recent updates have been at:  https://github.com/apache/incubator-zeppelin/pull/208 .
